trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
# Use Node.js version 16 (you can adjust this version)
- task: UseNode@2
  inputs:
    versionSpec: '16.x'  # You can specify the version as needed
    addToPath: true

# Install dependencies and clean npm cache
- script: |
    echo "Cleaning node_modules and npm cache"
    rmdir /s /q node_modules   # Removes node_modules folder for a clean slate
    npm cache clean --force    # Correctly clears npm cache with --force
  displayName: 'Clean node_modules and npm cache'

# Install npm dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Install Playwright Browsers
- script: |
    npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

# Run tests or other tasks
- script: |
    # Replace with your test commands, such as running Playwright tests
    npm test
  displayName: 'Run Tests'

# Additional steps like deployment or further build tasks go here
